## US Election Atlas scraped file cleanup

In [1]:
import pandas as pd
import ast
import numpy as np
import re

In [2]:
f = open("../DLAtl.jsonl")
LineReader = f.readlines()
f.close()

In [3]:
#Let's sample one line of our processed text data
LineReader[77]

'{"CandidateList": ["Obama", "Romney", "Other"], "County": "Chilton", "CandidatePartyCodeList": ["bardem", "barrep", "baroth"], "Year": "2012", "State": "Alabama", "CandidateVoteList": ["3,397", "13,932", "156"], "CandidatePctList": ["19.4%", "79.7%", "0.9%"]}\n'

In [4]:
#Trim the \n newline character off the end of each of the entries (except for the final entry)
for i in range(len(LineReader)-1):
    LineReader[i] = LineReader[i][:-1]
LineReader[77]

'{"CandidateList": ["Obama", "Romney", "Other"], "County": "Chilton", "CandidatePartyCodeList": ["bardem", "barrep", "baroth"], "Year": "2012", "State": "Alabama", "CandidateVoteList": ["3,397", "13,932", "156"], "CandidatePctList": ["19.4%", "79.7%", "0.9%"]}'

In [5]:
EvalList = []
for i in range(len(LineReader)):
    EvalList.append(ast.literal_eval(LineReader[i]))
    
EvalList[77]

{'CandidateList': ['Obama', 'Romney', 'Other'],
 'County': 'Chilton',
 'CandidatePartyCodeList': ['bardem', 'barrep', 'baroth'],
 'Year': '2012',
 'State': 'Alabama',
 'CandidateVoteList': ['3,397', '13,932', '156'],
 'CandidatePctList': ['19.4%', '79.7%', '0.9%']}

In [6]:
RestDataFrame = pd.DataFrame(EvalList)
RestDataFrame.iloc[77]

CandidateList               [Obama, Romney, Other]
CandidatePartyCodeList    [bardem, barrep, baroth]
CandidatePctList              [19.4%, 79.7%, 0.9%]
CandidateVoteList             [3,397, 13,932, 156]
County                                     Chilton
State                                      Alabama
Year                                          2012
Name: 77, dtype: object

In [7]:
RestDataFrame['State'].unique()
RestDataFrame['LengthsOK'] = np.nan

In [8]:
for i in range(len(RestDataFrame)):
    j = len(RestDataFrame['CandidateList'][i])
    k = len(RestDataFrame['CandidatePartyCodeList'][i])
    l = len(RestDataFrame['CandidatePctList'][i])
    m = len(RestDataFrame['CandidateVoteList'][i])
    if(j==k & j==l & j==m):
        RestDataFrame['LengthsOK'] = 0
    else:
        RestDataFrame['LengthsOK'] = 1

In [9]:
RestDataFrame[RestDataFrame['LengthsOK']>0].head()
sum(RestDataFrame['LengthsOK'])

0

In [10]:
#Let's expand the CuisinesList column. This procudes an expansion from 106974 to 302730 columns
IndexList = []
FlatCandList = []
FlatPartyCodeList = []
FlatPctList = []
FlatVotesList = []
index = 0
for item in RestDataFrame['CandidateList']:
    FlatCandList.extend(map(lambda x: x, item))
    IndexList.extend(map(lambda x: index, item))
    index += 1
for item in RestDataFrame['CandidatePartyCodeList']:
    FlatPartyCodeList.extend(map(lambda x: x, item))
    index += 1
for item in RestDataFrame['CandidatePctList']:
    FlatPctList.extend(map(lambda x: x, item))
    index += 1    
for item in RestDataFrame['CandidateVoteList']:
    FlatVotesList.extend(map(lambda x: x, item))
    index += 1    
    

ExpandedMerge = pd.DataFrame({'Index': IndexList, 'Candidate': FlatCandList, 'PartyCode': FlatPartyCodeList, 'VotePct': FlatPctList, 'VoteTotal': FlatVotesList})
ExpandedMerge.head(10)

ElectionResultsExpanded = pd.merge(RestDataFrame, ExpandedMerge, how='right', left_index=True, right_on='Index')
print(len(RestDataFrame))
print(len(ElectionResultsExpanded))
del ElectionResultsExpanded['CandidateList']
del ElectionResultsExpanded['CandidatePctList']
del ElectionResultsExpanded['CandidateVoteList']
del ElectionResultsExpanded['CandidatePartyCodeList']
del ElectionResultsExpanded['LengthsOK']
del ElectionResultsExpanded['Index']
ElectionResultsExpanded.head()

45717
156017

    County    State  Year Candidate PartyCode VotePct VoteTotal
0  Autauga  Alabama  2016   Clinton    bardem   23.8%     5,936
1  Autauga  Alabama  2016     Trump    barrep   72.8%    18,172
2  Autauga  Alabama  2016  McMullin    barind    0.0%         0
3  Autauga  Alabama  2016     Other    baroth    3.5%       865
4  Baldwin  Alabama  2016   Clinton    bardem   19.4%    18,458

In [22]:
LAAKCSV = pd.read_csv("../LouisianaAlaska.csv", header=None)
LAAKCSV.columns=['State', 'County', 'Year', 'PartyCode', 'Candidate', 'VoteTotal']
LAAKCSV.head(10)

    State    County  Year   PartyCode    Candidate  VoteTotal
0  Alaska  At Large  1996  Republican         Dole     122746
1  Alaska  At Large  1996  Democratic  Clinton (B)      80380
2  Alaska  At Large  1992  Republican    Bush (HW)     102000
3  Alaska  At Large  1992  Democratic  Clinton (B)      78294
4  Alaska  At Large  1988  Republican    Bush (HW)     119251
5  Alaska  At Large  1988  Democratic      Dukakis      72584
6  Alaska  At Large  1984  Republican       Reagan     138377
7  Alaska  At Large  1984  Democratic      Mondale      62007
8  Alaska  At Large  1980  Republican       Reagan      86112
9  Alaska  At Large  1980  Democratic       Carter      41842

In [23]:
JoinedTable = pd.concat([ElectionResultsExpanded, LAAKCSV])
JoinedTable.head(10)

C:\Users\Dave\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.

  Candidate   County PartyCode    State VotePct VoteTotal  Year
0   Clinton  Autauga    bardem  Alabama   23.8%     5,936  2016
1     Trump  Autauga    barrep  Alabama   72.8%    18,172  2016
2  McMullin  Autauga    barind  Alabama    0.0%         0  2016
3     Other  Autauga    baroth  Alabama    3.5%       865  2016
4   Clinton  Baldwin    bardem  Alabama   19.4%    18,458  2016
5     Trump  Baldwin    barrep  Alabama   76.5%    72,883  2016
6  McMullin  Baldwin    barind  Alabama    0.0%         0  2016
7     Other  Baldwin    baroth  Alabama    4.1%     3,874  2016
8   Clinton  Barbour    bardem  Alabama   46.5%     4,871  2016
9     Trump  Barbour    barrep  Alabama   52.1%     5,454  2016

In [27]:
print(len(ElectionResultsExpanded))
print(len(LAAKCSV))
print(len(JoinedTable))

156017
1300
157317

In [39]:
JoinedTable['PartyCode'] = JoinedTable['PartyCode'].replace(['bardem', 'barrep', 'barind', 'baroth'], ['Democratic', 'Republican', 'Indpendent', 'Other'])
JoinedTable['VotePct'] = JoinedTable['VotePct'].str.replace("%", "")
JoinedTable['VoteTotal'] = JoinedTable['VoteTotal'].str.replace(",", "")
JoinedTable['Year'] = pd.to_numeric(JoinedTable['Year'])
JoinedTable['VoteTotal'] = pd.to_numeric(JoinedTable['VoteTotal'])
JoinedTable.dtypes

Candidate     object
County        object
PartyCode     object
State         object
VotePct       object
VoteTotal    float64
Year           int64
dtype: object

In [40]:
#JoinedTable.to_csv('AllStates60to16AllParties.csv')

In [47]:
JoinedTable00to16 = JoinedTable[JoinedTable['Year']>1999]
JoinedTable00to16x = JoinedTable[JoinedTable['Year']<1999]
JoinedTable80to16DROnly = JoinedTable.query('PartyCode == "Democratic" or PartyCode == "Republican"')
JoinedTable00to16DROnly = JoinedTable00to16.query('PartyCode == "Democratic" or PartyCode == "Republican"')

In [48]:
print(len(JoinedTable))
print(len(JoinedTable00to16))
print(len(JoinedTable00to16x))
print(len(JoinedTable80to16DROnly))
print(len(JoinedTable00to16DROnly))

157317
52238
105079
92734
31138

In [50]:
JoinedTable[JoinedTable['State']=='Hawaii'].head(40)

      Candidate    County   PartyCode   State VotePct  VoteTotal  Year
25980   Clinton    Hawaii  Democratic  Hawaii    63.6    41259.0  2016
25981     Trump    Hawaii  Republican  Hawaii    27.0    17501.0  2016
25982  McMullin    Hawaii  Indpendent  Hawaii     0.0        0.0  2016
25983     Other    Hawaii       Other  Hawaii     9.4     6107.0  2016
25984   Clinton  Honolulu  Democratic  Hawaii    61.5   175696.0  2016
25985     Trump  Honolulu  Republican  Hawaii    31.6    90326.0  2016
25986  McMullin  Honolulu  Indpendent  Hawaii     0.0        0.0  2016
25987     Other  Honolulu       Other  Hawaii     6.9    19768.0  2016
25988   Clinton     Kauai  Democratic  Hawaii    62.5    16456.0  2016
25989     Trump     Kauai  Republican  Hawaii    28.8     7574.0  2016
25990  McMullin     Kauai  Indpendent  Hawaii     0.0        0.0  2016
25991     Other     Kauai       Other  Hawaii     8.8     2305.0  2016
25992   Clinton      Maui  Democratic  Hawaii    64.5    33480.0  2016
25993     Trump      Maui  Republican  Hawaii    25.9    13446.0  2016
25994  McMullin      Maui  Indpendent  Hawaii     0.0        0.0  2016
25995     Other      Maui       Other  Hawaii     9.7     5019.0  2016
25996     Obama    Hawaii  Democratic  Hawaii    74.4    47224.0  2012
25997    Romney    Hawaii  Republican  Hawaii    23.2    14753.0  2012
25998     Other    Hawaii       Other  Hawaii     2.3     1477.0  2012
25999     Obama  Honolulu  Democratic  Hawaii    68.9   204349.0  2012
26000    Romney  Honolulu  Republican  Hawaii    29.8    88461.0  2012
26001     Other  Honolulu       Other  Hawaii     1.3     3932.0  2012
26002     Obama     Kauai  Democratic  Hawaii    73.5    18641.0  2012
26003    Romney     Kauai  Republican  Hawaii    24.1     6121.0  2012
26004     Other     Kauai       Other  Hawaii     2.4      610.0  2012
26005     Obama      Maui  Democratic  Hawaii    74.1    36052.0  2012
26006    Romney      Maui  Republican  Hawaii    23.8    11602.0  2012
26007     Other      Maui       Other  Hawaii     2.1      999.0  2012
26008     Obama    Hawaii  Democratic  Hawaii    75.9    50819.0  2008
26009    McCain    Hawaii  Republican  Hawaii    22.2    14866.0  2008
26010     Other    Hawaii       Other  Hawaii     1.8     1231.0  2008
26011     Obama  Honolulu  Democratic  Hawaii    69.8   214239.0  2008
26012    McCain  Honolulu  Republican  Hawaii    28.7    88164.0  2008
26013     Other  Honolulu       Other  Hawaii     1.4     4410.0  2008
26014     Obama     Kauai  Democratic  Hawaii    75.0    20416.0  2008
26015    McCain     Kauai  Republican  Hawaii    22.9     6245.0  2008
26016     Other     Kauai       Other  Hawaii     2.1      563.0  2008
26017     Obama      Maui  Democratic  Hawaii    76.7    39727.0  2008
26018    McCain      Maui  Republican  Hawaii    21.5    11154.0  2008
26019     Other      Maui       Other  Hawaii     1.8      908.0  2008